//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServiceGizetdinov.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrashAuto_db
    {
        public int MainProductID { get; set; }
        public int AttachedProductID { get; set; }
    }
}
